### ISSUE TITLE
Parser error only in cosmo

### ISSUE THREAD

**Issue by step21** [SilentCicero/meteor-dapp-cosmo#7] opened 2015-06-17 17:55 UTC
Hi,

for some sol code I get a parser error, that does not happen with chriseth,github.io or solc binary. Only in cosmo. Any idea why?

```
:47:1: Parser error: Function, variable, struct or modifier declaration expected.

^
```

**Comment by step21** [comment] 2015-06-17 17:56
At line 47 there is just the final `}`

**Comment by SilentCicero** [comment] 2015-06-17 20:08
I'll update the compiler. I'm using an older edition that may have fixed this issue. Can you post the Solidity you were trying to run?

**Comment by step21** [comment] 2015-06-17 20:17
Not that it is super-special, but would prefer not to paste into github issues. Can I send it some other way?

**Comment by step21** [comment] 2015-06-18 16:04
Hi, so I posted it to pastebin now, hope that it is okay. http://pastebin.com/yAb7CSrd

**Comment by SilentCicero** [comment] 2015-06-18 22:26
So it seems your error is caused because your using term 'contract' within an event param. When you replace 'contract_address' with 'addr' for example, the error is resolved. I cant explain why the compiler is this way, but hopefully it is resolved with the latest compiler. 

As for other things I found, some of this error may be caused by bad characters, i.e. invalid spaces. I got your contract to work. Some of It I had to retype and space, but it compiled fine. Try removing and adjusting spaces. Retyping etc. This is an odd error, I'm not to sure why it happens.

I'll see what I can do to remove invalid spaces.

**Comment by step21** [comment] 2015-06-19 17:58
Ok, thanks. Yes, I think with an updated compiler it should be resolved, at least that was my impression on the chriseth.github.io/cpp-ethereum website which I think always uses latest commit.
Thanks for going through the trouble and checking for invalid characters. I just copy/pasted it, but was not aware of any steps that should have inserted invalid spaces/characters.

**Closed as completed** 2015-07-17 01:18 UTC
